### ISSUE TITLE
Typing `,`

### ISSUE THREAD

**Issue by stoivo** [lockevn/html-numeric-input#1]
You can type a , but is disappear on keyup, if you hold it. You will get more and they all disappear on keyup.

**Comment by lockevn** [comment]
I do not plan to support thousand separator like comma character ","

I don't think people used to type thousand separator when they are typing number. It is problem of the presentation, not typing.

**Comment by stoivo** [comment]
Oh, many european countries use , as a separator between pound and cent so
`1,234.56` would I type `1 234,56`.

**Comment by lockevn** [comment]
OK, I will make it configurable to use . or , for decimal separator.

**Comment by stoivo** [comment]
Cool.

**Comment by lockevn** [comment]
Call `toHtmlNumericInput('num', true)` if you want to use comma as decimal separator.

**Comment by premadh** [comment]
How about copy and paste? You can still copy and paste text to the area.
