### ISSUE TITLE
restricting numeric range

### ISSUE THREAD

**Issue by weedkiller** [lockevn/html-numeric-input#2]
hi, how can I ensure numeric value with a `decimal` between `0.0` to `24.0` I am unable to let it enter the `.`

**Comment by lockevn** [comment]
Hi,

By default, call `toHtmlNumericInput('num');` allow you to type . (the dot)

Ensure validating a decimal range is not purpose of this function. Sorry.

You are free to modify the code in `_OnNumericInputKeyUp(e)`

Add your validation on `v` before assigning it to `this.value`
`this.value = v; // update value only if we changed it`
